apiVersion: v1
kind: ConfigMap

metadata:
  name: patient-service-config

data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db-service:5432/db

  SPRING_JPA_HIBERNATE_DDL_AUTO: update

  SPRING_SQL_INIT_MODE: always